add-xml-decl: yes
doctype: transitional
output-xml: yes
wrap: 0
char-encoding: utf8
tidy-mark: no
write-back: yes
auto: true
server: true
safe: true
source: https://github.com/shamansir/gwt-mvp4g-layouting-demo
destination: _pages
lsi: false
pygments: true

